### ISSUE TITLE
Maximum heroes in custom games was increased months ago, add back the heroes that custom heroes replaced

### ISSUE THREAD

**Issue by szock** [CryDeS/AngelArena-Reborn#16]
**Ember Spirit** was replaced by _Fireblade_
**Blood Seeker** was replaced by _Spike_
**Sniper** was replaced by _Gun Joe_
**Terrorblade** was replaced by _Reaver Lord_
**Antimage** was replaced by _Shadowsong_
**Keeper of the Light** was replaced by _Hola_
**Vengeful Spirit** was replaced by _Joe Black_
**Doom** was replaced by _Satan_

There is no reason not to add these heroes back in now that the hero limit has been increased.  None of these heroes can farm faster than Mars, Kunkka, or Tidehunter so balance is not affected. 
Please add these heroes back in to the game.

**Comment by CryDeS** [comment]
Game plan is delete all basic dota content, so returning of dota heroes is not in plans.
